services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    bashit.install:
        class: Dotfiles\Plugins\BashIt\EventSubscriber
        tags:
            - { name: "event_subscriber" }
